<a href="https://colab.research.google.com/github/prabhashkumar289/Project/blob/main/IMDB_and_Amazon_Review_Classification_with_SpaCy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1) Importing the datasets

In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [62]:
data_yelp = pd.read_csv('yelp_labelled.txt', sep='\t', header=None)

In [63]:
data_yelp.head()
# review and sentiment 
# 0-Negative, 1-Positive for positive review

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [64]:
# Assign column names
columan_name = ['Review', 'Sentiment']
data_yelp.columns = columan_name

In [65]:
data_yelp.head()


Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [66]:
data_yelp.shape
# 1000 rows (reviews), 2 columns (Sentiments)

(1000, 2)

In [67]:
data_amazon = pd.read_csv('amazon_cells_labelled.txt', sep='\t', header=None)
 # importing dataset from file

In [68]:
data_amazon.head()
 # review and sentiment
 # 0-Negative, 1-Positive for Positive review

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [69]:
data_amazon.columns = columan_name
# insitilizing the head of database

In [70]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [71]:
data_amazon.shape

(1000, 2)

In [72]:
data_imdb = pd.read_csv('imdb_labelled.txt', sep='\t',header=None)
data_imdb.head()

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [73]:
data_imdb.columns = columan_name

In [74]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [75]:
data_imdb.shape

(748, 2)

In [76]:
# Append all the data in a single dataframe

In [77]:
data = data_yelp.append([data_amazon,data_imdb], ignore_index=True)

In [78]:
data.shape

(2748, 2)

In [79]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [80]:
# Check distribution of sentences

In [81]:
data['Sentiment'].value_counts()

# 1386 Positive reviews
# 1362 Negative reviews

1    1386
0    1362
Name: Sentiment, dtype: int64

In [82]:
# Check for null values

data.isnull().sum()

# no null valuesin the data

Review       0
Sentiment    0
dtype: int64

In [83]:
x = data['Review']
y = data['Sentiment']

# 2) Data Cleaning

In [30]:
# Here we will remove stopwords, punctuations
# As well as we will apply lemmatization

#Creating a function to clean the data

In [31]:
import string

In [32]:
punct = string.punctuation

In [33]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [34]:
from spacy.lang.en.stop_words import STOP_WORDS

In [35]:
stopwords = list(STOP_WORDS)  # LIST OF STOPWORDS

In [36]:
stopwords

['take',
 'top',
 'via',
 'all',
 'none',
 'anyone',
 'was',
 'except',
 'alone',
 'were',
 're',
 'used',
 'made',
 'same',
 'twelve',
 'two',
 'moreover',
 'am',
 'thereby',
 'side',
 'hence',
 '’s',
 'make',
 'nor',
 'had',
 'former',
 'him',
 'become',
 'mine',
 'cannot',
 'thence',
 'whereupon',
 'yours',
 'done',
 'then',
 'elsewhere',
 'nevertheless',
 '’ve',
 'meanwhile',
 'various',
 'along',
 'full',
 'above',
 'becoming',
 'also',
 'over',
 'beforehand',
 'regarding',
 'therefore',
 '’ll',
 'amongst',
 'amount',
 'are',
 'me',
 'beyond',
 'anywhere',
 'one',
 'bottom',
 'several',
 'throughout',
 'please',
 '’d',
 'call',
 'every',
 'during',
 'forty',
 'could',
 'still',
 'someone',
 'hundred',
 'although',
 'using',
 'even',
 '‘ve',
 'less',
 'while',
 'fifteen',
 'formerly',
 'if',
 'almost',
 'other',
 'neither',
 'should',
 'nine',
 'everything',
 'or',
 'must',
 'another',
 'either',
 'anyhow',
 'will',
 'any',
 'fifty',
 '’re',
 'since',
 'through',
 'thru',
 'third',

In [37]:
#creating a function for data cleaning

In [39]:
import spacy

nlp = spacy.load('en_core_web_sm')

def text_data_cleaning(sentence):
  doc = nlp(sentence)

  tokens = [] # list of tokens
  for token in doc:
    if token.lemma_ !="-PRON-":
      temp = token.lemma_.lower().strip()
    else:
      temp = token.lower_
    tokens.append(temp)

  cleaned_tokens = []
  for token in tokens:
    if token not in stopwords and token not in punct:
      cleaned_tokens.append(token)
  return cleaned_tokens    


In [42]:
# if root form of the word is not pronoun then it is going to convert that into lower form
# and if that word is a pronoun noun, then we are directly taking lower form, because there is no lemma in sentence

In [43]:
text_data_cleaning("Hello all, It's a beautiful day outside there!")

# stopwords and punctuation removed

['hello', 'beautiful', 'day', 'outside']

# Vectorization Feature Engineering(TF-IDF)

In [45]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [46]:
tfidf = TfidfVectorizer(tokenizer=text_data_cleaning)

# tokenizer=text_data_cleaning, tokenization will be done according to this function

In [47]:
classifier = LinearSVC()

# 3) Train the Model

Splitting the dataset into the Train and Test set

In [48]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [49]:
x_train.shape, x_test.shape

#2198 samples in training dataset and 550 in test dataset

((2198,), (550,))

In [50]:
x_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

Fit the x_trin and y_train

In [51]:
clf = Pipeline([('tfidf',tfidf), ('clf',classifier)])

# it will first do vectorization and then it will do classification

In [52]:
clf.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function text_data_cleaning at 0x7ff5bdf2fe60>,
                                 use_idf=True, vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept

In [53]:
# in this we don't need to prepare the dataset for testing(x_test)

# 4) Predict the Test set results

In [54]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [55]:
y_pred = clf.predict(x_test)

In [56]:
# confusion_matrix
confusion_matrix(y_test, y_pred)

array([[201,  78],
       [ 50, 221]])

In [57]:
# classification_report

print(classification_report(y_test, y_pred))

# we are getting almost 77% accuracy

              precision    recall  f1-score   support

           0       0.80      0.72      0.76       279
           1       0.74      0.82      0.78       271

    accuracy                           0.77       550
   macro avg       0.77      0.77      0.77       550
weighted avg       0.77      0.77      0.77       550



In [58]:
accuracy_score(y_test, y_pred)

# 76% accuracy

0.7672727272727272

In [59]:
clf.predict(["Woe, I am learning Natural Language processing in fun fashion!"])

# output is 1, that means review is positive

array([1])

In [60]:
clf.predict(["It's hard to learn new things!"])

#output is 0, that means review is Negative

array([0])